#!/bin/bash

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install git -y
sudo apt-get install htop -y
sudo apt-get install exuberant-ctags -y
sudo apt-get install nodejs npm -y
sudo ln -s /usr/bin/nodejs /usr/bin/node
git clone git@github.com:wellsjo/dotfiles.git ~/.dotfiles && source ~/.dotfiles/bash/profile && wells_install
