#!/bin/bash

# udpate, upgrade
sudo apt-get update -y
sudo apt-get upgrade -y

# insatll essentials
sudo apt-get install git -y
sudo apt-get install htop -y
sudo apt-get install default-jre -y
sudo apt-get install exuberant-ctags -y
sudo apt-get install nodejs npm -y

# use latest node
sudo npm install nave -g
nave usemain 4.1.1

# extensions
sudo npm install forever -g
sudo npm insatll js-beautify -g
sudo npm install jscs -g

# alias node to nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node

# dotfiles
git clone git@github.com:wellsjo/dotfiles.git ~/.dotfiles && source ~/.dotfiles/bash/profile && wells_install
